"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { useWorkout } from '@/context/WorkoutContext'
import { Brain, TrendingUp, AlertCircle, Lightbulb, Activity } from 'lucide-react'

export function AIInsights() {
  const { aiInsights } = useWorkout()

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'mobility':
        return <Activity className="h-4 w-4" />
      case 'form':
        return <TrendingUp className="h-4 w-4" />
      case 'recovery':
        return <AlertCircle className="h-4 w-4" />
      case 'strength':
        return <Lightbulb className="h-4 w-4" />
      default:
        return <Brain className="h-4 w-4" />
    }
  }

  const getPriorityVariant = (priority: string) => {
    switch (priority) {
      case 'high':
        return 'destructive'
      case 'medium':
        return 'default'
      case 'low':
        return 'secondary'
      default:
        return 'outline'
    }
  }

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'mobility':
        return 'bg-[hsl(var(--chart-1))]/10 [color:hsl(var(--chart-1))] border-[hsl(var(--chart-1))]/20'
      case 'form':
        return 'bg-[hsl(var(--chart-2))]/10 [color:hsl(var(--chart-2))] border-[hsl(var(--chart-2))]/20'
      case 'recovery':
        return 'bg-[hsl(var(--chart-3))]/10 [color:hsl(var(--chart-3))] border-[hsl(var(--chart-3))]/20'
      case 'strength':
        return 'bg-[hsl(var(--chart-4))]/10 [color:hsl(var(--chart-4))] border-[hsl(var(--chart-4))]/20'
      default:
        return 'bg-muted/50 text-muted-foreground border-border'
    }
  }

  // Sort by priority
  const sortedInsights = [...aiInsights].sort((a, b) => {
    const priorityOrder = { high: 0, medium: 1, low: 2 }
    return priorityOrder[a.priority] - priorityOrder[b.priority]
  })

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Brain className="h-5 w-5 text-primary" />
          <CardTitle>AI Coach Insights</CardTitle>
        </div>
        <CardDescription>
          Personalized recommendations based on your movement patterns and training data
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {sortedInsights.map((insight) => (
            <Alert
              key={insight.id}
              className={`${getCategoryColor(insight.category)} border`}
            >
              <div className="flex items-start gap-3">
                <div className="mt-0.5">
                  {getCategoryIcon(insight.category)}
                </div>
                <div className="flex-1 space-y-2">
                  <div className="flex items-start justify-between gap-2">
                    <h4 className="font-semibold leading-tight">
                      {insight.title}
                    </h4>
                    <Badge 
                      variant={getPriorityVariant(insight.priority)}
                      className="capitalize shrink-0"
                    >
                      {insight.priority}
                    </Badge>
                  </div>
                  <AlertDescription className="text-sm leading-relaxed">
                    {insight.description}
                  </AlertDescription>
                  <div className="pt-1">
                    <Badge variant="outline" className="capitalize text-xs">
                      {insight.category}
                    </Badge>
                  </div>
                </div>
              </div>
            </Alert>
          ))}
        </div>

        <div className="mt-6 pt-6 border-t">
          <div className="flex items-start gap-2 text-sm text-muted-foreground">
            <Brain className="h-4 w-4 mt-0.5 shrink-0" />
            <p>
              These insights are generated by analyzing your workout history, form scores, and movement patterns. 
              Check back regularly for updated recommendations.
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

